### PR TITLE
Mobile app: Remove async/await from JS code

### PR DESCRIPTION
**Pull request by dpalou**

### CODE REVIEW

**Comment by dpalou** [comment]
Hi Nicholas,

sorry to bother you again. Today I tested the app in an old Android device and I noticed that async/await doesn't work in those devices, so I had to remove that from the JS code of the plugin. Sorry for not testing this before sending the first PR.

**Comment by dpalou** [comment]
@crazyserver can you please take a look?

**Comment by crazyserver** [comment]
It seems ok for me! Thanks Dani!

**Comment by ndunand** [comment]
Hi Dani and Pau,

Sorry I was out of the office for a few days. Thanks for the code change, I'm merging and releasing now.

**Pull request merged**
