### PR TITLE
Adapt the mobile app code to Ionic 5

### PR DESCRIPTION
**Pull request by dpalou**
Hi Nicholas,

as you've probably heard, the mobile app code of plugins needs to be adapted to Ionic 5. Here are the changes to adapt the choicegroup plugin :)

Cheers,
Dani

### CODE REVIEW

**Comment by ndunand** [comment]
Hi @dpalou ,

Thanks! Yes indeed Juan mentioned it a few days ago. As you may not know, I don't have the expertise to review this properly. So should I just go on and release a new version including your changes?

**Comment by dpalou** [comment]
In that case I'll ask @crazyserver to review my code, just to be sure I haven't done anything wrong.

**Review by crazyserver — CHANGES_REQUESTED** [review]
Hi Dani! 

I've just reviewed your code and found only one minor problem with the sync and refresh icons. Please review it before integrating this code.

Cheers!

**Comment by dpalou** [comment]
Thanks Pau, nice catch! I changed them.

@ndunand I think the code is now ready to be integrated :)

This new code won't be needed until we release the version 3.9.5 of the app in late June, so if you were planning to do a release soon with other changes you can wait and release it all at once, as you prefer.

**Comment by ndunand** [comment]
Thanks @dpalou and @crazyserver !

Planning a new release for Moodle 3.11 but just in case I'm a little late on the release schedule, this is backward compatible, right ? So I could simply release these changes immediately.

**Comment by dpalou** [comment]
Yes, it's backwards compatible, the plugin will work as it used to in the current app so you can release it now.

**Comment by ndunand** [comment]
Alright, merged and releasing now. Thanks agains for your work and for sharing.

**Pull request merged**
