### PR TITLE
Accessibility for Group choosing

### PR DESCRIPTION
**Pull request by crazyserver**
Hi Nicolas,

I've seen the changes from version 2.6 to 2.8 and I'm working on some accessibility changes.

I took some code from a similar plugin: https://github.com/IOC/moodle-mod_choosegroup

If you agree this changes I will continue translating the strings and editing the JS code.

Tell me what you think, the code is not ready to be merged.

Cheers,

### CODE REVIEW

**Comment by ndunand** [comment]
Hi,

Thanks for sharing this. What changes are you implementing exactly?

**Comment by crazyserver** [comment]
:+1: 
When editing the activity the choice of the groups became very confusing. I tried to write a more accessible form to choose the groups and its options. I has some work to do but you can test it to see if it seems good to you and I'll finishe it early.

**Comment by ndunand** [comment]
OK, I just quickly tried it out. But how do you define which groups are to be used?

**Comment by crazyserver** [comment]
All except those that have a 0 as limit. I can change the nolimit checkbox by a use group checkbox and then if 0 is specified then it will have no limit. In the other hand, we can use two checkboxes by group but is not a good idea...

It will need contextual help as well.

**Comment by crazyserver** [comment]
I've made some more changes.
- If you set 0 as limit it will consider it has no limit
- Checkboxes to add groups in use
screenshot-choicegroup

Please, could you review it and tell me what do you think?

Cheers,

**Pull request closed without merging**
