### PR TITLE
fix issue #108

### PR DESCRIPTION
**Pull request by s-cenni**
Hi Nicolas,
this is the solution I found to fix this bug: "YUI JavaScript errors on responses page".

### CODE REVIEW

**Comment by ndunand** [comment]
Thanks @s-cenni. I haven't had much time to deal with this lately but this looks like https://github.com/ndunand/moodle-mod_choicegroup/pull/111/commits/d4569bf402d12bb23b9983efb6069b4951f4105f#diff-25eb2cfd41b242f700f7c778c4416c17R330 implies a dependency on mod_choice, which should then be documented in version.php.

Any way to do without this dependency ?

**Comment by s-cenni** [comment]
Hi @ndunand! The old library was removed in 3.3 (https://tracker.moodle.org/browse/MDL-57490). I think the better solution to avoid the dependency is to include the new JS library in the Group Choice plugin. 
Do you agree?

**Comment by adpe** [comment]
Hello @ndunand @s-cenni 
What you can do is, provide the JS direct in this plugin. So you have no dependencies on other plugins.

**Comment by ndunand** [comment]
Sorry @s-cenni I missed your last reply. Yes, incluging the JS library in this plugin sounds better to me.

**Pull request closed without merging**
