### PR TITLE
Clarified system default sort option

### PR DESCRIPTION
**Pull request by andrewhancox**
From Alex:
The "Sort groups by" widget in the activity settings gives three options: System default, ID, Name. User's won't know what the system default is and will probably choose a fixed setting although this would not be necessary. Could you please change your PR that the widget says "System default (ID)" respectively "System default (Name)"?
At least I don't find this change in the (now merged) pull request.

I've changed the language slightly - I added 'Currently' so the user will appreciate that the system default may change.

### CODE REVIEW

**Comment by ndunand** [comment]
Thanks Andrew!

**Comment by abias** [comment]
Thanks, Nicolas, for merging this second pull request. May I ask you again to put the new version to the Moodle plugin repo so that we can translate the new strings in AMOS?

Thanks,
Alex

**Comment by ndunand** [comment]
All right, here we go!
10f7564fb93ac53d89ce4b0bcfc99bb74290dea0 and https://moodle.org/plugins/pluginversion.php?id=8070

**Comment by abias** [comment]
Perfect, thanks!

Alex

**Pull request merged**
