### PR TITLE
#168 fix lost groups to choose while restore

### PR DESCRIPTION
**Pull request by adamtppaw**

### CODE REVIEW

**Comment by cdipe** [comment]
@NicoAlexH I tested the new version now, and the link to the Group choice in copied course is now gone - but it looks like this: The two already added groups are still under "Available groups". (Nothing happens when selecting them and clicking Add)
group choice in restored course
groups in restored course

**Comment by cdipe** [comment]
@NicoAlexH @adamtppaw I tested this in my local MAMP Moodle 4.1.1 too, same problem - shows already added groups as selectable.

**Comment by NicoAlexH** [comment]
@cdipe I'm sorry, I can't seem to reproduce ; are you sure you unchecked the "groups and groupings" option when restoring the course ? 

To clarify, this is what I did on my part : 

1 - Create a course with students, groups and a choicegroup module
2 - Have the students select groups in the choicegroup module
3 - Backup the course without the students
4 - Restore to a new course (unchecking the "groups and groupings" option)

=> In the newly created course, there are no groups.

I also tried to restore the course, this time checking the option "groups and groupings" (4th step).

=> In the new course, I see the same groups that existed in the original course, and the "Add" button for adding participants works fine.

May I suggest you to open a new issue if you think this is abnormal, including the steps to reproduce the bug ? Thank you !

**Comment by cdipe** [comment]
Hi @NicoAlexH !
It works fine. We do the restore with the groups and groupings included (no users, though) and it still works fine, the right groups are selectable for the students in the restored course's Group Choice. 

I think I just explained badly, and I may remember wrong how Group Choice used to work:

- When adding groups in Group Choice administration, from _Available Groups_ to _Selected groups_, they still remain in the Available groups menu. 

- The expected behaviour would be that when added to _Selected groups_, they disappear from _Available groups_. And, if removed from _Selected groups_, they should show under _Available groups_ again.

The behaviour is the same if it's a copied course with Group Choice, or an new Group Choice in an new course.
I'll report this as a new issue, or, if it's always been this way, as an improvement suggestion.
Allt the best, 
Peter

**Pull request merged**
